name 'themis-finals'
description 'Installs and configures Themis Finals'
version '2.2.2'

recipe 'themis-finals', 'Installs and configures Themis Finals'
depends 'git'
depends 'git2', '~> 1.0.0'
depends 'database', '~> 6.1.1'
depends 'poise-python', '>= 1.6.0'
depends 'rbenv', '1.7.1'
depends 'supervisor', '~> 0.4.12'
depends 'nginx'
depends 'ssh-private-keys', '~> 2.0.0'
depends 'ssh_known_hosts'
depends 'yarn', '~> 0.4.0'
depends 'themis-finals-utils', '~> 1.2.0'
depends 'instance', '~> 2.0.0'
depends 'secret', '~> 1.0.0'
depends 'localdns', '~> 1.3.0'
depends 'htpasswd', '~> 0.3.0'
depends 'graphicsmagick', '~> 0.1.0'
depends 'netdata', '~> 0.4.1'
depends 'patch', '~> 2.2.1'

depends 'themis-finals-customize-default', '~> 1.0.0'
depends 'volgactf-2018-final-customizer', '~> 1.0.0'
